# Generated by Django 4.2.6 on 2023-10-30 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='author_name',
            new_name='client_name',
        ),
        migrations.AddField(
            model_name='chat',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='author_name',
            field=models.CharField(default='name', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[(0, 'Ожидает'), (1, 'Активен'), (2, 'Закрыт')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
