# Generated by Django 4.2.6 on 2023-10-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ожидает'), (1, 'Активен'), (2, 'Закрыт')], default=0),
        ),
    ]
