# Generated by Django 4.2.6 on 2023-10-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='client_name',
        ),
    ]
