# Generated by Django 4.2.6 on 2023-10-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chat_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
