# Generated by Django 4.2.6 on 2023-10-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chat_sk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='created_by',
        ),
        migrations.AddField(
            model_name='message',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
    ]
