# Generated by Django 4.2.6 on 2023-10-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastUserAddress',
        ),
    ]
